# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
title: "Staff Software Engineer | Machine Learning Portfolio"
email: saich.work@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: saichn
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # Adjust this value based on how many projects you want to showcase per page
paginate_path: /page:num/
timezone: "America/New_York" # Set your timezone accordingly

include:
  - _pages
  - _projects # Include a folder for projects

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-assets # Optional: For better asset management, if needed

author:
  name: "Sai Chaitanya Nandipati"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Dynamic software developer with over 8 years of experience in creating efficient applications and optimizing automation processes. With a master’s degree in Computer Science focused on Machine Learning, I am eager to leverage my software expertise to drive innovative solutions in the AI field."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/saichnandipati/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saichn"
    
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/saichnandipati/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saichn"
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Projects section
projects:
  title: "My Projects"
  description: "Explore my work in Machine Learning and AI, showcasing innovative solutions and applications."
  items:
    - title: "Transfer Learning with AlexNet for Cricket Shot Classification"
      url: "https://github.com/saichn/Transfer-Learning-with-AlexNet-for-Cricket-Shot-Classification"
      description: "A project that utilizes transfer learning techniques with AlexNet for cricket shot classification, achieving high accuracy in shot detection."

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

